### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Martin2145** [MintPond/node-hasher-mtp#2]
Hi,

Ubuntu 16.04
Node 8.16

Everything built without issue, index.js give no error, yet i've got a Segmentation fault (core dumped) with 

~/node-hasher-mtp# node test.js
Finding nonce...
Segmentation fault (core dumped)

Thanks

**Comment by Martin2145** [comment]
valgrind output:

Finding nonce...
==6645== Invalid read of size 8
==6645==    at 0x98E18C1: copy_block (in /root/node-hasher-mtp/build/Release/hashermtp.node)
==6645==    by 0x98EA933: mtp::compute_blake2b(block_ const&, unsigned char*) (in /root/node-hasher-mtp/build/Release/hashermtp.node)
==6645==    by 0x98EAD28: mtp::hash(char const*, unsigned int, unsigned int&, unsigned int, unsigned char*, unsigned long (*) [128], std::deque<std::vector<unsigned char, std::allocator<unsigned char> >, std::allocator<std::vector<unsigned char, std::allocator<unsigned char> > > >*, uint256&) (in /root/node-hasher-mtp/build/Release/hashermtp.node)
==6645==    by 0x98F9E62: hash(Nan::FunctionCallbackInfo<v8::Value> const&) (in /root/node-hasher-mtp/build/Release/hashermtp.node)
==6645==    by 0x98F9784: Nan::imp::FunctionCallbackWrapper(v8::FunctionCallbackInfo<v8::Value> const&) (in /root/node-hasher-mtp/build/Release/hashermtp.node)
==6645==    by 0xA98152: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /root/.nvm/versions/node/v8.16.0/bin/node)
==6645==    by 0xB0F37B: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /root/.nvm/versions/node/v8.16.0/bin/node)
==6645==    by 0xB0FFCE: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /root/.nvm/versions/node/v8.16.0/bin/node)
==6645==    by 0x2F1BEBE842FC: ???
==6645==    by 0x2F1BEBF3EDB5: ???
==6645==    by 0x2F1BEBF3EDB5: ???
==6645==    by 0x2F1BEBF3EDB5: ???

**Comment by JCThePants** [comment]
The segmentation fault could be because you don't have enough memory.
